rules/ng_angularelement.js
The comment is for `ng_definedundefined.js` which already has this comment
=> remove comment

rules/ng_controller_name.js, test/ng_controller_name.js
I haven't found a way to use RegExps in JSON formatted .eslintrc, but this adds support for them. Should fix #68.
=> add support for regexps from JSON .eslintrc

demo/grunt/package.json
I was trying to run the grunt version of the demo and was getting "Fatal error: Unable to find local grunt." when running grunt from the terminal. I noticed it was including the grunt-cli package instead of grunt itself. So, I updated that and set the eslint-plugin-angular version to match the other demos.
Nice job on the plugin, I'm hoping to get my company using it for our Angular apps.
=> Fix grunt version of demo

rules/ng_no_services.js, test/ng_no_services.js
This PR provides three way of configuration and resolves #88:
1\. just a list of services (as it was)
```
'ng_no_services': [2, ['$http', '$resource', 'Restangular']]
```
2\. a list of services and a list of angular objects
```
'ng_no_services': [2, ['$http', '$resource', 'Restangular'], ['controller', 'factory']]
```
3\. angular objects and services for each of them
```
'ng_no_services': [2, {controller: ['$http', '$q'], factory: ['Restangular']}]
```
=> make angular object list configurable for ng_no_services

rules/ng_on_watch.js, test/ng_on_watch.js
Do not require capturing of $destroy handlers.
Allow $on handlers to be captured directly in $destroy handlers in
addition to assigning to variables.
Fixes #107
=> Be more lenient with $destroy in ng_on_watch.

README.md
PR onto development. Sorry about that.
=> docs(readme) add eslint-config-angular usage

README.md, rules/ng_di_order.js, test/ng_di_order.js
It is weird to enforce the order `$http, $httpBackend` in a factory, while enforcing `_$httpBackend_, _$http_` in unittests.
=> Ng di order underscores

README.md, index.js, rules/directive-restrict.js, test/directive-restrict.js
There are some corner cases. For example when setting a property named `restrict` to another object inside of a directive declaration. I think this is rare though.
Closes #23
=> Add rule for enforcing directive restrictions

README.md, index.js, rules/no-inline-template.js, test/no-inline-template.js
Templates are considered too complex if they consist of more than one html template or escape a character using a backslash.
Closes #58
=> Add rule disallowing inline templates

gulpfile.js, package.json, rules/utils/utils.js, test/utils/utils.js
I think these patches uncover some issues with the utils. Also the utils are untested.
I would like to make tests for them and fix those issues if I'm sure I've got the documentation right.
=> Utils restructure

rules/on-watch.js, test/on-watch.js
Changes to increase the statement coverage to 100%.
The problem with the current almost 100% coverage is that removing lines in other parts of the source lead to a relative coverage decrease. 805/808 is a higher coverage than 800/803.
https://coveralls.io/builds/3828298
=> Increase coverage

rules/function-type.js, rules/utils/utils.js, test/function-type.js
=> Issue 229/function type rule does not recognize inline named functions properly

rules/function-type.js, test/function-type.js
some components were not checked by the rule.
Most prominent one: ``directive``
=> Apply function-type rule to all viable components

rules/di-unused.js, test/di-unused.js
Now di-unused does not check usage of deps if we rite in array notation our services:
```js
angular.module('foo', []).controller('MyController', ['$http', function($http){...}]);
```
this patch should fix it.
Thanks!
=> feat(di-unused): check unused deps in array notation

.eslintrc, docs/component-limit.md, examples/component-limit.js, rules/component-limit.js, rules/di-order.js, rules/di-unused.js, rules/utils/angular-rule.js, test/component-limit.js, test/di-order.js, test/di-unused.js
I'm writing a rule wrapper which makes it easier to write some AngularJS related rules.
The goal is that common rule definitions don't have to implement the same common checks and lookups individually. Also this should help fixing common false positives.
Ultimately I think it is possible to achieve a wrapper which can resolve variables using ESLint scopes and understands the following are AngularJS components:
```js
var myApp = angular.module('myApp').factory('toyFactory', function() {});
myApp.filter('parentalControl', parentalControlFilter);
function parentalControlFilter() {}
```
Whereas these are not:
```js
_.filter(obj, coffeeFilter);
mocha.run();
```
Currently the component extraction is handled by each rule separately, which grealy impacts performance. For this reason this PR …
=> Angular rule

rules/utils/angular-rule.js, test/di-order.js, test/di-unused.js
This affects the rules `di-order` and `di-unused`.
This fixes the same issue as #277, but using `angularRule`.
=> Check injected functions using array notation

README.md, scripts/templates.js, scripts/templates/readmeRuleSectionContent.template.md
The PR contains only small docs changes. We could release a 0.14.1 version to make the improvement available faster.
=> add short link to styleguide in rule section (#288)

README.md, docs/no-run-logic.md, examples/no-run-logic.js, index.js, rules/no-run-logic.js, test/no-run-logic.js
This closes #53.
@Gillespie59 @tilmanpotthof PTAL
=> Add new rule for disallowing run logic

docs/typecheck-array.md, examples/typecheck-array.js
=> add missing example for typecheck-array (fixes #291)

.eslintrc, rules/file-name.js, rules/utils/rulesConfiguration.js, scripts/docs.js
I figured enforcing `global-require` makes sense. On the other hand I have my doubts, since it adds some `eslint-disable-line` comments as well.
@tilmanpotthof Feel free to either merge or close this.
=> Enfore eslint rule global-require

.travis.yml, README.md, docs/dumb-inject.md, examples/dumb-inject.js, index.js, rules/dumb-inject.js, test/dumb-inject.js
=> Add new dumb-inject rule

README.md, docs/no-digest.md, docs/typecheck-regexp.md, rules/no-digest.js, rules/typecheck-regexp.js, scripts/docs.js, scripts/templates/ruleDocumentationContent.template.md
PR for #295 
- interpret deprecated annotation in the docs task
- add deprecated section to rule documentation template
- add deprecated annotation to no-digest and typecheck-regexp rules
=> add deprecated annotation to documentation (fixes #295)

package.json
This closes #316.
If I'm correct, the `contributors` field should replace `author`. (https://docs.npmjs.com/files/package.json#people-fields-author-contributors)
=> Add contributors to package.json

README.md, index.js, rules/controller-name.js, test/controller-name.js
Default configurations are no longer supported in `eslint@^2.0.0`.
I ran into some issues removing this.
I can fix the following pretty easily:
- Tests appear to be using non-primitive types. This is not supported in a JSON schema / ESLint configuration [JSON Schema primitive types](http://json-schema.org/latest/json-schema-core.html#anchor8)
I can work around this:
- Unlike a live run of ESLint, the rule tester does seem to use the `rulesConfig`.
I'm not sure what to do about this:
- `rulesConfig` is used to generate the defaults section in the readme. @tilmanpotthof I believe you created the scripts that generate this. Could you take a look at this? Should I just make all defaults turn to zeroes for this PR?
There are more rules having defaults. I'll remove these in upcoming commits in …
=> Remove default configurations

README.md
I don't know why defaults config removed,
Please prepare a change log for those who are upgrading  from 0.15.0 to 1.0.0.
=> Remove link to #defaults from readme

rules/file-name.js, test/file-name.js
The following example:
```
/*eslint angular/file-name: [2,{"typeSeparator":"dot","nameStyle":"dash","ignoreTypeSuffix":true}]*/
//
// Before fix
// invalid with filename: yii2-message.directive.js
angular.directive('yii2Message', []);
// valid with filename: yii2message.directive.js
angular.directive('yii2Message', []);
//
// After fix
// valid with filename: yii2-message.directive.js
angular.directive('yii2Message', []);
// invalid with filename: yii2message.directive.js
angular.directive('yii2Message', []);
```
=> Fixed issue when names are composite numbers.

rules/directive-restrict.js, test/directive-restrict.js
First of all, I think you all have done an awesome work here, so Congrats.
Now the reason for this PR is because for an eCommerce app I'm working on we need to support IE8, so short story is that we need to restrict directive by Attribute and / or Class only so I found this plugin which has a lot of good rules, specially directive-restrict one which has pretty much most of what I need but it as some limitations ( by design ) as it follows {johnpapa} `y074` Restrict to Elements and Attributes guideline. So I made some changes so it still support's johnpapa rule plus a way to "bend" a bit the restriction list to accommodate more scenarios like the one I have.
More information on angular directive and IE8 issues here: http://stackoverflow.com/questions/19611280/directive-not-working-in-ie8 …
=> Update directive-restrict rule to support restriction by Class

rules/controller-name.js
closes #359
the current version misses the `^` making sure the FIRST letter is upper case, not just any letter before the string `Controller`. Also, using `.*` in between, allows for non-UpperCamelCase namings, including special characters.
=> correct regexp for UpperCamelCase / Y123

rules/utils/utils.js, test/directive-name.js, test/filter-name.js, test/no-controller.js, test/no-service-method.js
When using Angular with Browserify, or another module loader system, the linter should be able to dectect components that are required from another file. 
Expanded the isAngularComponent method to also allow CallExpression nodes.
=> Change isAngularComponent to also capture require("")

docs/di-order.md
According to the rule's source and the given examples, the parameter has to be set to `true` to strip underscores while checking.
*corresponding rule-code:*
```JavaScript
var stripUnderscores = context.options[0] !== false;
// [...]
if (stripUnderscores) {
formattedArg = formattedArg.replace(/^_(.+)_$/, '$1');
}
```
=> di-order.md: Corrected the description

rules/prefer-component.js, test/prefer-component.js
... when the value of "restrict" is not a string literal.
```js
angular.module('myModule').directive('myDirective', 
function() {
return {
restrict: foo, // This is usually a string literal, e.g. "EA"
...
};
}]);
```
The bug was discovered while checking this code snippet.
http://stackoverflow.com/a/29010910/437
=> Fixes a crash on prefer-component

docs/component-name.md, examples/component-name.js, rules/utils/utils.js, test/component-name.js
Updates the code regarding component-names as it uses the wrong signature in examples and checking.
From angular documentation:
.component() takes two parameters name as string and a config object.
=> Align with angular component api

docs/constant-name.md, docs/factory-name.md, docs/provider-name.md, docs/service-name.md, docs/value-name.md, examples/constant-name.js, examples/factory-name.js, examples/provider-name.js, examples/service-name.js, examples/value-name.js, rules/constant-name.js, rules/factory-name.js, rules/module-getter.js, rules/provider-name.js, rules/service-name.js, rules/utils/utils.js, rules/value-name.js, test/constant-name.js, test/factory-name.js, test/provider-name.js, test/service-name.js, test/value-name.js
=> Change `service-name` rule to apply only `angular.Module#service` - (WIP)

docs/timeout-service.md, examples/timeout-service.js, rules/timeout-service.js, test/timeout-service.js
=> issue 434 - $window support in timeout-service

rules/service-name.js
Related to #431 
Also when there was no `oldBehavior` at all since it's default to `true`
=> service-name warn only once if there is an oldBehavior=true

rules/directive-restrict.js, test/directive-restrict.js
Related to issue #494
Enhanced the ``directive-restrict`` rule to support these registration flavours (split statements):
Array notation:
```javascript
app.directive("snapContainer", ['$scope', myDirective]);
function myDirective($scope) {
return {
restrict:   "A"
}
}		
```
Simple notation with ``ngInject``:
```javascript
app.directive("snapContainer", myDirective);
/* @ngInject */
function myDirective($rootScope) {
return {
restrict:   "A"
}
}
```
=> Enhance directive restrict rule to allow split statement for directive registration

rules/directive-restrict.js, test/directive-restrict.js
Reverts Gillespie59/eslint-plugin-angular#495
=> Revert "Enhance directive restrict rule to allow split statement for directive registration"

rules/di.js
Without this, eslint may throw `TypeError: Cannot read property 'length' of undefined` on otherwise valid files.
=> Ensure that fn.params is defined.

rules/no-directive-replace.js, test/no-directive-replace.js
Fix #541 
This case below caused a crash in the plugin.
```
angular.
module('contact.contactShow.dashboardSite').
directive('siteDashboard', () => ({replace:true})
);
angular.
module('contact.contactShow.dashboardSite').
directive('siteDashboard', function () {() => ({replace:true}); return {replace:true}}
);
angular.
module("dsds").
directive('siteDashboard', function SiteDashboardDirective () {
return {
template,
restrict: 'E',
scope: true,
replace:true
};
});
```
I had to add ecmascript version 6 to the RuleTester to being able to add test cases with arrow function without getting parsing error.
I have no idea if the plugin should support this version of ecmascript and if this is the optimal solution for this kind of problem.
You can use the test code above to see that it's working and …
=> Fix arrow function problem no directive replace

rules/function-type.js, test/function-type.js, test/utils/commonFalsePositives.js
Hello,
These changes alter the default option used by the `angular/function-type` rule so that named functions are preferred over anonymous ones. This alteration is in line with John Papa's style guidance for AngularJS ([Y024][]).
Also had to fiddle with the test suite a bit to ensure it stayed green.
[Y024]: https://github.com/johnpapa/angular-styleguide/tree/master/a1#style-y024
=> Change default function-type rule option to prefer named functions

rules/avoid-scope-typos.js, test/avoid-scope-typos.js
=> Fix issue with "bad" keyword in object and function definition

docs/rules/file-name.md, examples/file-name.js, rules/file-name.js, rules/utils/utils.js, test/file-name.js
Solves issue: #534 
This PR will make it possible to use regexp in the ignorePrefix option for the file-name rule.
This is because people want to have custom ignoring,
Examples:
Ignore multiple prefixes.
Change the ignoring for modules.
=> Implement regexp for file name rule

rules/di-unused.js, test/di-unused.js
**Before fix:**
Using `angular.module("").factory("", function factory($q) {});` will find no linting errors when using di-unused linting rule.
**After fix:**
Using `angular.module("").factory("", function factory($q) {});` will find $q as an unused di.
=> Add scope type check to fix problem with function names for di-unused.

package.json
Having the `angular` keyword in this AngularJS NPM package may be misleading for people who are looking for Angular specific packages.
=> docs(package): remove angular keyword
