EmmanuelDemey/eslint-plugin-angular

rules/ng_controller_name.js, rules/ng_directive_name.js, rules/ng_filter_name.js, rules/ng_module_name.js, rules/ng_service_name.js, rules/utils/utils.js, test/ng_controller_name.js, test/ng_directive_name.js, test/ng_filter_name.js, test/ng_module_name.js, test/ng_service_name.js
Add support for directives, filters, services, and modules. Move
logic to utils.
=> add regexp support for JSON .eslintrc

README.md
We just made a release using this plugin - in case you'd like to list more users.
=> add generator-ng-poly to list of users

rules/utils/utils.js, test/ng_controller_as_route.js
=> Fix for missing null check in calling identifier function

rules/ng_on_watch.js, test/ng_on_watch.js
Hi !
I think there is a mistake in the ng_watch_on rule since it doesn't look for $on and $watch function calls but on and watch which does not exist in angular
=> Fix/ng $watch $on

rules/ng_di_order.js, test/ng_di_order.js
Fixed some issues which I resolved when actually using this rule live.
=> Ng di order

rules/controller-name.js, test/controller-name.js
=> Allow getting a controller by a directive name in tests

README.md, index.js, rules/component-limit.js, test/component-limit.js
=> Add a rule for setting a component per file limit

rules/no-service-method.js, test/no-service-method.js
=> no-service-method: remove unnecessary options (#248)

rules/no-service-method.js, test/no-service-method.js
Failing test and fix for missing property check #252
=> Issue 252/type error for describe block with no service method rule

test/module-getter.js
=> Add test case for failing case for module-getter

rules/di-unused.js, test/di-unused.js
Reverts Gillespie59/eslint-plugin-angular#277
This shouldn't have been merged into the master branch. Also this would cause merge conflicts with #257 if merged into the development branch.
=> Revert "feat(di-unused): check unused deps in array notation"

README.md
The development branch wasn't even mentioned at all.
I just guessed a bit on how @Gillespie59 handles releases.
=> Describe the branching model a bit in the readme

docs/one-dependency-per-line.md, examples/one-dependency-per-line.js, scripts/docs.js, scripts/templates/ruleDocumentationContent.template.md
=> Issue 268/example parser does not allow examples with multiple errors

README.md
@Gillespie59 Now you don't have to feel alone in that Team section.
@tilmanpotthof If you agree of course.
=> Add Tilman Potthof and Remco Haszing to the team

README.md, index.js, scripts/docs.js, scripts/templates/defaultsRuleSectionContent.template.md
=> Generate defaults in readme and index.js

rules/di.js, test/di.js
=> Issue/329 angular/di rule false positive when function has no dependencies

README.md, docs/component-limit.md, docs/controller-as-vm.md, docs/module-dependency-order.md, examples/module-dependency-order.js, index.js, rules/component-limit.js, rules/controller-as-vm.js, rules/di.js, rules/no-services.js, rules/watchers-execution.js
This closes #344.
Also, see #345.
=> Remove remaining ruleconfigs

README.md
Reverts Gillespie59/eslint-plugin-angular#355
=> Revert "Remove link to #defaults from readme"

README.md
Same as #355 but this one is to dev branch.
=> Remove link to #defaults from readme [ci-skip]

README.md, docs/component-name.md, examples/component-name.js, rules/component-name.js, rules/utils/utils.js, test/component-name.js
Similar to directive-name rule
=> Add component-name rule

rules/file-name.js, test/file-name.js
Here are the unit tests.  If I need to un-do both of these and submit them as one commit, let me know.
=> Issue 452/angular/file name/casing/unit tests

rules/di.js, test/di.js
=> Allow the stripping of underscores from DI parameters

rules/directive-restrict.js
=> Add check for null in directive-restrict

rules/utils/utils.js, test/component-name.js
=> Allow component name to be identifier

docs/rules/function-type.md, rules/function-type.js
=> fix: avoid false positive on function-type rule
